import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../../../core/network/api_client.dart';
import '../domain/session_model.dart';
import '../domain/two_factor_setup_data.dart';

part 'settings_repository.g.dart';

/// Repository for Settings-related API calls.
///
/// Covers FR91: active session listing and per-session revocation.
/// Covers FR60: account deletion (server queues 30-day soft-delete per NFR-R7).
/// Covers FR81: data export (returns signed ZIP download URL).
/// Covers FR92: 2FA setup, confirmation, and disable.
///
/// ARCH RULE: Always injected via Riverpod — never instantiated directly.
/// Use `ref.watch(settingsRepositoryProvider)` in providers.
class SettingsRepository {
  const SettingsRepository(this._apiClient);

  final ApiClient _apiClient;

  /// Fetches the list of active sessions for the authenticated user.
  ///
  /// `GET /v1/auth/sessions`
  /// Returns each session with `sessionId`, `deviceName`, `location`,
  /// `lastActiveAt`, and `isCurrentDevice`.
  Future<List<SessionModel>> getSessions() async {
    final response = await _apiClient.dio.get<Map<String, dynamic>>(
      '/v1/auth/sessions',
    );
    final data = response.data;
    if (data == null) return [];
    final list = data['data'] as List<dynamic>? ?? [];
    return list
        .map((e) => SessionModel.fromJson(e as Map<String, dynamic>))
        .toList();
  }

  /// Revokes (deletes) the refresh token for the given [sessionId].
  ///
  /// `DELETE /v1/auth/sessions/:sessionId`
  /// Returns normally on success (204 No Content).
  /// Throws [DioException] on error (403 self-lockout, 404 not found).
  Future<void> deleteSession(String sessionId) async {
    await _apiClient.dio.delete<void>('/v1/auth/sessions/$sessionId');
  }

  // ---------------------------------------------------------------------------
  // Data export (FR81)
  // ---------------------------------------------------------------------------

  /// Requests a data export archive for the current user.
  ///
  /// `POST /v1/users/me/export`
  /// Returns a [downloadUrl] pointing to the generated ZIP archive (CSV + Markdown).
  /// The URL is a signed R2 URL valid for a limited time.
  /// Throws [DioException] on failure.
  Future<String> requestDataExport() async {
    final response = await _apiClient.dio.post<Map<String, dynamic>>(
      '/v1/users/me/export',
    );
    final data = response.data?['data'] as Map<String, dynamic>?;
    final url = data?['downloadUrl'] as String?;
    if (url == null || url.isEmpty) {
      throw Exception('Export URL not returned from server');
    }
    return url;
  }

  // ---------------------------------------------------------------------------
  // Account deletion (FR60, NFR-R7)
  // ---------------------------------------------------------------------------

  /// Triggers account deletion for the current user.
  ///
  /// `DELETE /v1/users/me`
  /// Server queues a 30-day soft-delete per NFR-R7 — user data is not
  /// immediately purged. Returns normally (204) on success.
  /// Throws [DioException] on failure.
  Future<void> deleteAccount() async {
    await _apiClient.dio.delete<void>('/v1/users/me');
  }

  // ---------------------------------------------------------------------------
  // Two-factor authentication (FR92)
  // ---------------------------------------------------------------------------

  /// Initiates 2FA setup for the current user.
  ///
  /// `POST /v1/auth/2fa/setup`
  /// Returns a [TwoFactorSetupData] containing the TOTP secret, QR code URI,
  /// and a list of one-time backup codes. The secret and backup codes are only
  /// shown once — the user must save them before confirming setup.
  Future<TwoFactorSetupData> setup2FA() async {
    final response = await _apiClient.dio.post<Map<String, dynamic>>(
      '/v1/auth/2fa/setup',
    );
    final data = response.data?['data'] as Map<String, dynamic>?;
    if (data == null) throw Exception('2FA setup data not returned from server');
    return TwoFactorSetupData(
      secret: data['secret'] as String? ?? '',
      otpauthUri: data['otpauthUri'] as String? ?? '',
      backupCodes: (data['backupCodes'] as List<dynamic>? ?? [])
          .map((e) => e as String)
          .toList(),
    );
  }

  /// Confirms 2FA setup by verifying the first TOTP code from the authenticator app.
  ///
  /// `POST /v1/auth/2fa/confirm`
  /// [totpCode] is the 6-digit code generated by the authenticator app for the
  /// secret returned by [setup2FA]. Returns `true` on success, `false` on invalid code.
  Future<bool> confirm2FA(String totpCode) async {
    try {
      await _apiClient.dio.post<Map<String, dynamic>>(
        '/v1/auth/2fa/confirm',
        data: {'code': totpCode},
      );
      return true;
    } catch (_) {
      return false;
    }
  }

  /// Disables 2FA for the current user.
  ///
  /// `DELETE /v1/auth/2fa`
  /// [totpCode] is required to prevent accidental or unauthorized disable.
  /// Returns normally (204) on success. Throws [DioException] on failure.
  Future<void> disable2FA(String totpCode) async {
    await _apiClient.dio.delete<void>(
      '/v1/auth/2fa',
      data: {'code': totpCode},
    );
  }
}

/// Riverpod provider for [SettingsRepository].
///
/// Every consumer must use this — never construct [SettingsRepository] directly.
@riverpod
SettingsRepository settingsRepository(Ref ref) {
  final client = ref.watch(apiClientProvider);
  return SettingsRepository(client);
}

/// Riverpod provider that loads the active sessions list.
///
/// Exposes `AsyncValue<List<SessionModel>>` — use `.when(...)` in widgets.
@riverpod
Future<List<SessionModel>> activeSessions(Ref ref) {
  final repo = ref.watch(settingsRepositoryProvider);
  return repo.getSessions();
}
